# whitelisted branches
branches:
  only:
    - master
    - develop

language: node_js
node_js:
 # - "node" 
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"


script: npm run test:only && npm test

after_success:
  - npm run test:cover
  - bash <(curl -s https://codecov.io/bash)
  
sudo: false
